<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        static $currencies = [
            // description, symbol, code
            ['Afghan afghani','؋','AFN'],
            ['Albanian lek','L','ALL'],
            ['Algerian dinar','د.ج','DZD'],
            ['Angolan kwanza','Kz','AOA'],
            ['Argentine peso','$','ARS'],
            ['Armenian dram','֏','AMD'],
            ['Aruban florin','ƒ','AWG'],
            ['Australian dollar','$','AUD'],
            ['Bahamian dollar','$','BSD'],
            ['Bahraini dinar','.د.ب','BHD'],
            ['Bangladeshi taka','৳','BDT'],
            ['Barbadian dollar','$','BBD'],
            ['Belarusian ruble','Br','BYN'],
            ['Belize dollar','$','BZD'],
            ['Bermudian dollar','$','BMD'],
            ['Bhutanese ngultrum','Nu.','BTN'],
            ['Bitcoin','₿','BTC'],
            ['Bolivian boliviano','Bs.','BOB'],
            ['Bosnia and Herzegovina convertible mark','KM','BAM'],
            ['Botswana pula','P','BWP'],
            ['Brazilian real','R$','BRL'],
            ['British pound','£','GBP'],
            ['Brunei dollar','$','BND'],
            ['Bulgarian lev','лв.','BGN'],
            ['Burmese kyat','Ks','MMK'],
            ['Burundian franc','Fr','BIF'],
            ['Cambodian riel','៛','KHR'],
            ['Canadian dollar','$','CAD'],
            ['Cape Verdean escudo','$','CVE'],
            ['Cayman Islands dollar','$','KYD'],
            ['Central African CFA franc','Fr','XAF'],
            ['CFP franc','₣','XPF'],
            ['Chilean peso','$','CLP'],
            ['Chinese yuan','¥','CNY'],
            ['Colombian peso','$','COP'],
            ['Comorian franc','Fr','KMF'],
            ['Congolese franc','Fr','CDF'],
            ['Cook Islands dollar','$','CKD'],
            ['Costa Rican colón','₡','CRC'],
            ['Croatian kuna','kn','HRK'],
            ['Cuban peso','$','CUP'],
            ['Czech koruna','Kč','CZK'],
            ['Danish krone','kr','DKK'],
            ['Djiboutian franc','Fr','DJF'],
            ['Dominican peso','RD$','DOP'],
            ['Eastern Caribbean dollar','$','XCD'],
            ['Egyptian pound','£','EGP'],
            ['Eritrean nakfa','Nfk','ERN'],
            ['Ethiopian birr','Br','ETB'],
            ['Euro','€','EUR'],
            ['Falkland Islands pound','£','FKP'],
            ['Faroese króna','kr','FOK'],
            ['Fijian dollar','$','FJD'],
            ['Gambian dalasi','D','GMD'],
            ['Ghanaian cedi','₵','GHS'],
            ['Gibraltar pound','£','GIP'],
            ['Guatemalan quetzal','Q','GTQ'],
            ['Guernsey pound','£','GGP'],
            ['Guinean franc','Fr','GNF'],
            ['Guyanese dollar','$','GYD'],
            ['Haitian gourde','G','HTG'],
            ['Honduran lempira','L','HNL'],
            ['Hong Kong dollar','$','HKD'],
            ['Hungarian forint','Ft','HUF'],
            ['Icelandic króna','kr','ISK'],
            ['Indian rupee','₹','INR'],
            ['Indonesian rupiah','Rp','IDR'],
            ['Iranian rial','﷼','IRR'],
            ['Iraqi dinar','ع.د','IQD'],
            ['Israeli new shekel','₪','ILS'],
            ['Jamaican dollar','$','JMD'],
            ['Japanese yen','¥','JPY'],
            ['Jersey pound','£','JEP'],
            ['Jordanian dinar','د.ا','JOD'],
            ['Kazakhstani tenge','₸','KZT'],
            ['Kenyan shilling','Sh','KES'],
            ['Kiribati dollar','$','KID'],
            ['Kuwaiti dinar','د.ك','KWD'],
            ['Kyrgyzstani som','с','KGS'],
            ['Lao kip','₭','LAK'],
            ['Lebanese pound','ل.ل','LBP'],
            ['Lesotho loti','L','LSL'],
            ['Liberian dollar','$','LRD'],
            ['Libyan dinar','ل.د','LYD'],
            ['Macanese pataca','MOP$','MOP'],
            ['Macedonian denar','ден','MKD'],
            ['Malagasy ariary','Ar','MGA'],
            ['Malawian kwacha','MK','MWK'],
            ['Malaysian ringgit','RM','MYR'],
            ['Maldivian rufiyaa','.ރ','MVR'],
            ['Manx pound','£','IMP'],
            ['Mauritanian ouguiya','UM','MRU'],
            ['Mauritian rupee','₨','MUR'],
            ['Mexican peso','$','MXN'],
            ['Moldovan leu','L','MDL'],
            ['Mongolian tögrög','₮','MNT'],
            ['Moroccan dirham','د.م.','MAD'],
            ['Mozambican metical','MT','MZN'],
            ['Namibian dollar','$','NAD'],
            ['Nepalese rupee','रू','NPR'],
            ['Netherlands Antillean guilder','ƒ','ANG'],
            ['New Taiwan dollar','$','TWD'],
            ['New Zealand dollar','$','NZD'],
            ['Nicaraguan córdoba','C$','NIO'],
            ['Nigerian naira','₦','NGN'],
            ['North Korean won','₩','KPW'],
            ['Norwegian krone','kr','NOK'],
            ['Omani rial','ر.ع.','OMR'],
            ['Pakistani rupee','₨','PKR'],
            ['Panamanian balboa','B/.','PAB'],
            ['Papua New Guinean kina','K','PGK'],
            ['Paraguayan guaraní','₲','PYG'],
            ['Peruvian sol','S/.','PEN'],
            ['Philippine peso','₱','PHP'],
            ['Pitcairn Islands dollar','$','PND'],
            ['Polish złoty','zł','PLN'],
            ['Qatari riyal','ر.ق','QAR'],
            ['Romanian leu','lei','RON'],
            ['Russian ruble','₽','RUB'],
            ['Rwandan franc','Fr','RWF'],
            ['Saint Helena pound','£','SHP'],
            ['Samoan tālā','T','WST'],
            ['São Tomé and Príncipe dobra','Db','STN'],
            ['Saudi riyal','﷼','SAR'],
            ['Serbian dinar','дин.','RSD'],
            ['Seychellois rupee','₨','SCR'],
            ['Sierra Leonean leone','Le','SLL'],
            ['Singapore dollar','$','SGD'],
            ['Solomon Islands dollar','$','SBD'],
            ['Somaliland shilling','Sl','SLS'],
            ['Somali shilling','Sh','SOS'],
            ['South African rand','R','ZAR'],
            ['South Korean won','₩','KRW'],
            ['South Sudanese pound','£','SSP'],
            ['Sudanese pound','ج.س.','SDG'],
            ['Surinamese dollar','$','SRD'],
            ['Swazi lilangeni','L','SZL'],
            ['Swedish krona','kr','SEK'],
            ['Swiss franc','Fr.','CHF'],
            ['Syrian pound','£','SYP'],
            ['Tajikistani somoni','с.','TJS'],
            ['Tanzanian shilling','Sh','TZS'],
            ['Thai baht','฿','THB'],
            ['Tongan paʻanga','T$','TOP'],
            ['Transnistrian ruble','р.','PRB'],
            ['Trinidad and Tobago dollar','$','TTD'],
            ['Tunisian dinar','د.ت','TND'],
            ['Turkish lira','₺','TRY'],
            ['Turkmenistan manat','m.','TMT'],
            ['Tuvaluan dollar','$','TVD'],
            ['Ugandan shilling','Sh','UGX'],
            ['Ukrainian hryvnia','₴','UAH'],
            ['United Arab Emirates dirham','د.إ','AED'],
            ['United States dollar','$','USD'],
            ['Uruguayan peso','$','UYU'],
            ['Uzbekistani soʻm','Sʻ','UZS'],
            ['Vanuatu vatu','Vt','VUV'],
            ['Venezuelan bolívar soberano','Bs.','VES'],
            ['Vietnamese đồng','₫','VND'],
            ['West African CFA franc','Fr','XOF'],
            ['Yemeni rial','﷼','YER'],
            ['Zambian kwacha','ZK','ZMW'],
        ];

        foreach ($currencies as $currency) {
            DB::table('currencies')->insert([
                'description' => ucWords($currency[0]),
                'symbol' => $currency[1],
                'code' => $currency[2],
            ]);
        }
    }
}
